### ISSUE TITLE
docker: build all-in-one binary for docker images

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2280]
I think we'd better have 4 images:

ghcr.io/singularity-data/risingwave:latest -> risingwave single binary
ghcr.io/singularity-data/risingwave-meta-node:latest -> meta node
ghcr.io/singularity-data/risingwave-compute-node:latest -> compute node
ghcr.io/singularity-data/risingwave-frontend-node:latest -> frontend node

So that users can choose how to compose their docker-compose file easily. If they only want to run playground, they don't even need a docker-compose file:

```
docker exec ghcr.io/singularity-data/risingwave:latest -- playground
```

If they want to compose all services, currently, we have to write all configs in docker-compose.yml. But we expect that the Dockerfile itself should already contain all such configs.

https://github.com/singularity-data/risingwave/blob/f5b6189f616eb306f31751451e1b6c3c3e1d47d6/docker/docker-compose.yml#L33-L43

In the future, we can simply:

```yaml
  compute-node:
    image: ghcr.io/singularity-data/risingwave-compute-node:latest
    volumes:
      - ./src/config:/risingwave/config
    depends_on:
      - meta-node
```

where the bootstrap command, expose ports are all configured in Dockerfile instead of by users.
