### ISSUE TITLE
bug: notification stream terminated when the cluster has multiple compactors

### ISSUE THREAD

**Issue by hzxa21** [singularity-data/risingwave#4869]
### Describe the bug

commit id: `1b59d2c247d62e28b11bfd26325b72767751571d`

When starting up a cluster with 2 compactors, I saw `Stream of notification terminated.` flooding the logs for both compactors. This indicates that the notification streaming rpc fails and re-subscription is triggered, which is not expected.

### To Reproduce

Same as #4868 

### Expected behavior

No error logs on notification stream.

### Additional context

![image (3)](https://user-images.githubusercontent.com/5518566/186487213-a6eee467-8d73-483c-9b9d-22a1743b6c22.png)
![image (2)](https://user-images.githubusercontent.com/5518566/186487223-d9b89980-133b-4651-ab23-e82fa7cd0534.png)

**Comment by hzxa21** [comment]
After I stop one compactor, `Stream of notification terminated.` stops. I guess we somehow assign the same worker id for the two compactors. This may also be the root cause of #4868

**Comment by hzxa21** [comment]
cc @soundOfDestiny Can you help on this issue?

**Comment by hzxa21** [comment]
[meta-node.log](https://github.com/singularity-data/risingwave/files/9421123/meta-node.log)

**Comment by Gun9niR** [comment]
How did you start up the cluster? I ran two compactors on the same node and cannot reproduce the problem.

**Comment by hzxa21** [comment]
Confirmed that two compactors are assigned the same worker id. I suspect two compactors report the same address+port to meta on startup.
![image](https://user-images.githubusercontent.com/5518566/186572143-1afef92d-7ef9-439e-bcd5-05797f632d42.png)

**Comment by hzxa21** [comment]
> How did you start up the cluster? I ran two compactors and meta on the same node and cannot reproduce the problem.

I modify risedev-bench to let terraform provisions two ec2 instances for compactors and start-up RisingWave cluster using the following risedev config:
```
compose-3cn-2compactor-deploy:
    - use: aws-s3
      bucket: ${terraform:s3-bucket}

    - use: meta-node
      id: meta-node-0
      address: ${dns-host:rw-meta-0}
      listen-address: "0.0.0.0"

    - use: compute-node
      id: compute-node-0
      listen-address: "0.0.0.0"
      address: ${dns-host:rw-compute-0}
      enable-async-stack-trace: true

    - use: compute-node
      id: compute-node-1
      listen-address: "0.0.0.0"
      address: ${dns-host:rw-compute-1}
      enable-async-stack-trace: true

    - use: compute-node
      id: compute-node-2
      listen-address: "0.0.0.0"
      address: ${dns-host:rw-compute-2}
      enable-async-stack-trace: true

    - use: frontend
      id: frontend-node-0
      listen-address: "0.0.0.0"
      address: ${dns-host:rw-meta-0}

    - use: compactor
      id: compactor-0
      listen-address: "0.0.0.0"
      address: ${dns-host:rw-compactor-0}
      max-concurrent-task-number: 15
      compaction-worker-threads-number: 15

    - use: compactor
      id: compactor-01
      listen-address: "0.0.0.0"
      address: ${dns-host:rw-compactor-1}
      max-concurrent-task-number: 15
      compaction-worker-threads-number: 15

    - use: prometheus
      id: prometheus-0
      listen-address: "0.0.0.0"
      address: ${dns-host:rw-meta-0}

    - use: grafana
      listen-address: "0.0.0.0"
      address: ${dns-host:rw-meta-0}
      id: grafana-0
```

I also verified that `rw-compactor-0` and `rw-compactor-1` have different ip and dns addresses.
